name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Fix permissions
      run: sudo chown -R $(whoami) /home/action/actions-runner/_work/class-running/class-running

    - uses: actions/checkout@v4
      with:
        clean: false

    - name: Build Docker images
      run: docker compose build

    - name: Run Docker Compose
      run: docker compose up -d
