name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
      with:
        clean: false
    - name: Build Docker images
      run: docker compose build
    - name: Run Docker Compose
      run: docker compose up -d
