name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Set up Docker Compose
      uses: docker/setup-buildx-action@v2
    - name: Build Docker images
      run: sudo docker compose build
    - name: Run Docker Compose
      run: sudo docker compose up -d
